# Generated by Django 4.2.16 on 2025-03-13 12:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[('1', 'Мужской'), ('2', 'Женский')])),
                ('place', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('check_in', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 1, 1))])),
                ('check_out', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 1, 1))])),
                ('status', models.IntegerField(choices=[('1', 'Забронировано'), ('2', 'Внесена предоплата'), ('3', 'Полностью оплачен'), ('4', 'Заселен')])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_breakfast', models.BooleanField(blank=True, null=True)),
                ('has_lunch', models.BooleanField(blank=True, null=True)),
                ('has_dinner', models.BooleanField(blank=True, null=True)),
                ('tour_type', models.IntegerField(choices=[('1', 'Социальная путевка по контракту (льгота)'), ('2', 'Обычная путевка за свои деньги'), ('3', 'Только проживание')])),
                ('prepayment_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prepayment_money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1908, 6, 8)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2025, 3, 13))])),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[('1', 'Двухкомнатный номер на 1 этаже в 4 корпусе с удобствами в номере'), ('2', 'Двухместный номер на 1 этаже в 4 корпусе с удобствами в блоке'), ('3', 'Двухместный номер на 1 этаже в 4 корпусе с удобствами в номере'), ('4', 'Одноместный номер на 1 этаже в 4 корпусе с удобствами в номере'), ('5', 'Двухместный номер на 2 этаже в 4 корпусе с удобствами в блоке'), ('6', 'Двухместный номер на 1 этаже в 6 корпусе с удобствами в номере'), ('7', 'Двухместный номер на 2 этаже в 6 корпусе с удобствами в номере')])),
                ('tour_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('floor', models.IntegerField(choices=[('1', '1 этаж'), ('2', '2 этаж')])),
                ('building', models.IntegerField(choices=[('4', '4 корпус'), ('5', '5 корпус'), ('6', '6 корпус')])),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('category', models.IntegerField(choices=[('1', 'Двухкомнатный номер на 1 этаже в 4 корпусе с удобствами в номере'), ('2', 'Двухместный номер на 1 этаже в 4 корпусе с удобствами в блоке'), ('3', 'Двухместный номер на 1 этаже в 4 корпусе с удобствами в номере'), ('4', 'Одноместный номер на 1 этаже в 4 корпусе с удобствами в номере'), ('5', 'Двухместный номер на 2 этаже в 4 корпусе с удобствами в блоке'), ('6', 'Двухместный номер на 1 этаже в 6 корпусе с удобствами в номере'), ('7', 'Двухместный номер на 2 этаже в 6 корпусе с удобствами в номере')])),
                ('room_type', models.IntegerField(choices=[('1', 'Удобства в номере'), ('2', 'Удобства на этаже')])),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[('1', 'Забронировано'), ('2', 'Внесена предоплата'), ('3', 'Полностью оплачен'), ('4', 'Заселен')])),
                ('gender', models.IntegerField(choices=[('1', 'Мужской'), ('2', 'Женский'), ('3', 'Не указан'), ('4', 'Желательно мужской'), ('5', 'Желательно женский')])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.IntegerField(choices=[('1', 'Социальная путевка по контракту (льгота)'), ('2', 'Обычная путевка за свои деньги'), ('3', 'Только проживание')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(117)])),
                ('gender', models.IntegerField(choices=[('1', 'Мужской'), ('2', 'Женский')])),
                ('building', models.IntegerField(choices=[('4', '4 корпус'), ('5', '5 корпус'), ('6', '6 корпус')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('home_address_country', models.CharField(max_length=30)),
                ('home_address_region', models.CharField(max_length=30)),
                ('home_address_city', models.CharField(max_length=30)),
                ('home_address_street_and_house', models.CharField(max_length=70)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.room')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.room'),
        ),
    ]
